language: c
os: linux
dist: trusty
sudo: required

before_install:
  # Add cross-tools APT repository
  - curl http://vincent.riviere.free.fr/debian/GPG-key.txt | sudo apt-key add -
  - echo "deb http://vincent.riviere.free.fr/debian/ $(lsb_release -cs) contrib" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  # Install additional packages
  - sudo apt-get install -y cross-mint-essential dos2unix
  # Display packages versions
  - git --version
  - make --version
  - ld --version
  - gcc --version
  - m68k-atari-mint-ld --version
  - m68k-atari-mint-gcc --version
  - tar --version
  - unix2dos --version

script:
  - VERSION=$(date +%Y%m%d)~$(git rev-parse --short $TRAVIS_COMMIT)
  - make clean
  - make release VERSION=$VERSION
  - ls -l release-archives

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FCO2YMnZpVF7dzMC9w+aX0Wf44uyThplY3QG5vIr2vDPmCV5NBDbG9a/WZaA1RQsbtcNWFbJYvulPMlu7hR+4LHbQLmjz9XtIH1KQ5qSFn2WieUBiCF+NciukBp3d2kcFiHpm2pJ+DPaRt95S7FyurhStGy0BJus7j+qU0F8eScMQFJ/FUI+NeY2yYLMm6AF20TvcZkZhYbp56f46epki9HHgsWxpW2aMHJ8/HvRcxB4q0cdx8J21lu1LqwbPHeKx0bOENciM1tn8L44z1Gu3fWLsSm/GSWwVB80VIKBEZAnbokiKNzflb2c4r+TIOZyCEsNS6qGGZyfuWJeEw79PDLRHbsNcgYDj2W3y1ASFgCAx9Ad1DOeG0Et/+qw/LceGKG1aegoJn8hx15vjWb74evMCJg7/KVZBmbUD1/bj1wpuZIGRUI0NYKfo6qNEf0zph4MiAVTRNeN21zK+9amlKC2xs6DE/hmep6X9CwbDFGNgbqUij43dX/VE8x7sRST4Sg3upiGktubqOk5Yxwq1JU1MTbh9aJ3B4PcSkFkJbUsowndonB/Wx+Utepa1fyReLRp4TtDeVU8AhjYl7+8zl7MgUutGAPusl7Z364eWY3d+8Q3OHvue0vNiGQpE9ZBMfQcTherz7Mia0asjRQF52bSmvJEUY/L5eFfLIT1O5o=
  file_glob: true
  file: release-archives/*
  on:
    repo: vinriviere/emutos
